---
title: Xu Deng
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
author: Xu Deng
description: 'There is always room for improvement.

'
baseurl: ''
url: http://xden.github.io
github_username: d8660091
excerpt_separator: "<!-- more -->"
markdown: kramdown
gems:
- jekyll-seo-tag
- jekyll-sitemap
- jekyll-octicons
