title: Xu Deng
description:
  Xu Deng's blog
baseurl: ""
url: "http://xden.github.io"
author: Xu Deng
# twitter_username: xdeng
github_username: d8660091
excerpt_separator: <!-- more -->

# Build settings
markdown: kramdown

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post

gems:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-octicons
